name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flatpak
        run: |
          sudo apt update
          sudo apt install flatpak flatpak-builder -y
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak --version
          flatpak-builder --version

      - name: Install platform and SDK for flatpak
        run: sudo flatpak install --assumeyes flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08

      - name: Install tweego
        run: make install

      - name: Build the story `story.twee`
        run: make run

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  publish:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
